leftnav:
- identifier: external--1233975944-1698166802782
  name: Online Publication
  url: https://d-lab.mit.edu/research/past-research-projects-programs/energy-needs-assessment-toolkit
  weight: 10
